### ISSUE TITLE
Scratch font license

### ISSUE THREAD

**Issue by djsrv** [LLK/scratch-render-fonts#22]
I've seen quite a few posts like [this one](https://scratch.mit.edu/discuss/post/3464208/) stating that were issues with licensing the Scratch font, and this prevented it from being used in new costumes. Right now, this repo only has a single OFL.txt license file. This seems to imply that every font here is licensed under the OFL 1.1, and as this is an open-source license, this seems to contradict that other information.

Is the Scratch font licensed so that it's okay to distribute with forks of Scratch? If it isn't licensed under the OFL, maybe it should have its own license file?

**Comment by BryceLTaylor** [comment]
Closing in favor of https://github.com/LLK/scratch-render-fonts/issues/23
